### ISSUE TITLE
Splitting DSMR attrs to seperate DSMR messages

### ISSUE THREAD

**Issue by ekaats** [Lalufu/p1-mqtt#4]
For use with Home Assistant (https://www.home-assistant.io/integrations/dsmr_reader), attributes need to be parsed and send as separate DSMR messages. A DSMR parser already exists [available](https://github.com/ndokter/dsmr_parser) which is used by [another](https://github.com/dulfer/dsmr2mqtt/tree/main) project.

I could write a pull request to add this functionality, if you don't mind the extra dependency. One thing I would want to do different compared to the example above is to not assume elements to be available in the DSMR telegram. For example, multiple phases, gas and tariffs depend on that info being available on the meter. If not, it will not be outputted. The DSMR parser exposes an iterator which would work nicely. I'm planning on just running through that, and create a mapping based on the [HA integration](https://github.com/home-assistant/core/blob/dev/homeassistant/components/dsmr_reader/definitions.py).

**Comment by Lalufu** [comment]
If your final goal is to integrate this with Home Assistant, this might
not be the right tool for the job. The DSMR tools you linked to seem to
follow a different message structure, and while you could add this to
this tool as additional fields, using one of the already existing tools
seems less hassle?

**Comment by ekaats** [comment]
That's true, but I need to adapt the one I linked as well to work with my use-case.  Though you may be right. I first thought they made some hard-coded choices that work for them specifically, but may actually be more generic than I thought. I'll have another look at their solution and will decide which to contribute to.
